networks:
  caddy_net:
    external: true

services:
  caddy:
    image: caddy:2-built
    container_name: caddy
    restart: unless-stopped
    environment:
      MCADMIN_PORT: ${MCADMIN_PORT:-8080}
      MCMAP_PORT: ${MCMAP_PORT:-8081}
      KUNO_PORT: ${KUNO_PORT:-8082}
      VPN_PORT: ${VPN_PORT:-8083}
      TRANSLATE_PORT: ${TRANSLATE_PORT:-8084}
      MUSIC_PORT: ${MUSIC_PORT:-8085}
      MUSIC_HGM_PORT: ${MUSIC_HGM_PORT:-8086}
      ZEROBYTE_PORT: ${ZEROBYTE_PORT:-8087}
    volumes:
      - ./global-caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_root_data:/data
      - caddy_root_config:/config
    networks:
      - caddy_net

  newt:
    image: fosrl/newt
    container_name: newt
    restart: unless-stopped
    environment:
      - PANGOLIN_ENDPOINT=${PANGOLIN_ENDPOINT:-}
      - NEWT_ID=${NEWT_ID:-}
      - NEWT_SECRET=${NEWT_SECRET:-}
    networks:
      - caddy_net

volumes:
  caddy_root_data:
  caddy_root_config:

