networks:
  caddy_net:
    external: true

services:
  caddy:
    image: caddy:2-built
    container_name: caddy
    restart: unless-stopped
    environment:
      MINECRAFT_DYNMAP_SERVER_ADDRESS: ${MINECRAFT_DYNMAP_SERVER_ADDRESS:-minecraft-dynmap.example.com}
      MINECRAFT_DYNMAP_PORT: ${MINECRAFT_DYNMAP_PORT:-8123}
      MINECRAFT_ADMIN_SERVER_ADDRESS: ${MINECRAFT_ADMIN_SERVER_ADDRESS:-minecraft-admin.example.com}
      MINECRAFT_ADMIN_PORT: ${MINECRAFT_ADMIN_PORT:-8080}
      KUNO_SERVER_ADDRESS: ${KUNO_SERVER_ADDRESS:-blog.example.com}
      KUNO_PORT: ${KUNO_PORT:-8081}
      ZEROBYTE_SERVER_ADDRESS: ${ZEROBYTE_SERVER_ADDRESS:-backup.example.com}
      ZEROBYTE_PORT: ${ZEROBYTE_PORT:-8083}
      MUSIC_SERVER_ADDRESS: ${MUSIC_SERVER_ADDRESS:-music.example.com}
      MUSIC_PORT: ${MUSIC_PORT:-8085}
      TRANSLATE_SERVER_ADDRESS: ${TRANSLATE_SERVER_ADDRESS:-translate.example.com}
      TRANSLATE_PORT: ${TRANSLATE_PORT:-5000}
      CF_API_TOKEN: ${CF_API_TOKEN:-}
    #ports:
    #  - "${HTTP_PORT:-80}:80"
    #  - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./caddy-global/Caddyfile:/etc/caddy/Caddyfile
      - caddy_root_data:/data
      - caddy_root_config:/config
    networks:
      - caddy_net
  netbird:
    image: netbirdio/netbird:0.73.2
    container_name: netbird
    hostname: ${NB_HOSTNAME:-My Server}
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    cpu_shares: 90
    command: [
      "service",
      "run",
      "--setup-key=${NB_SETUP_KEY}",
      "--route=0.0.0.0/0"
    ]
    deploy:
      resources:
        limits:
          memory: "8224227328"
        reservations:
          memory: "134217728"
          devices: []
    environment:
      - NB_ALLOW_SERVER_SSH=true
      - NB_ENABLE_SSH_ROOT=true
      - NB_HOSTNAME=${NB_HOSTNAME:-My Server}
      - NB_MANAGEMENT_URL=${NB_MANAGEMENT_URL:?Set NB_MANAGEMENT_URL in .env}
      - NB_SETUP_KEY=${NB_SETUP_KEY:?Set NB_SETUP_KEY in .env}
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/NetBird/icon.svg
    restart: unless-stopped
    volumes:
      - type: bind
        source: $BASE_DATA_PATH/netbird
        target: /var/lib/netbird
    ports: []
    devices: []
    privileged: false

volumes:
  caddy_root_data:
  caddy_root_config: